

# Project information
site_name: "Smarthome Doku"
site_url: "https://smarthome.ms1.de"
site_description: "Doku zu Home Assistant und sonstigen smarten Basteleien"
site_author: "saruter"
copyright: "Copyright 2019-2020 - saruter. Creative Commons Attribution 4.0."

# Repository
repo_name: "Github"
repo_url: "https://github.com/saruter/smarthome"
edit_uri: ""

theme: 
  name: "readthedocs"
  custom_dir: "rtd-custom"
#theme: "rtd-mklab"
#theme: "rtd-dropdown"
#theme: "bootstrap"


